ping -c 5 google.com
ping -c 3 yahoo.com
ping -c 2 bbc.co.uk
ping -c 5 hotmail.com
ping -c 3 reddit.com
ping -c 5 archive.org
ping -c 5 suny.edu
ping -c 3 slickdeals.net
ping -c 8 yahoo.com
ping -c 8 espn.com
ping -c 5 bbc.co.uk
ping -c 5 hotmail.com
ping -c 2 ask.com
ping -c 3 reddit.com
ping -c 5 archive.org
ping -c 5 suny.edu
ping -c 7 slickdeals.net
ping -c 3 google.com
ping -c 4 espn.com
ping -c 4 ask.com
ping -c 3 google.com
ping -c 4 yahoo.com
ping -c 5 hotmail.com
ping -c 5 suny.edu
ping -c 5 slickdeals.net
ping -c 3 dealnews.com
ping -c 4 ubuntu.com
ping -c 8 ask.com
ping -c 2 google.com
ping -c 8 yahoo.com
ping -c 5 bbc.co.uk
ping -c 5 hotmail.com
ping -c 3 yahoo.com
ping -c 6 espn.com
ping -c 3 reddit.com
ping -c 5 archive.org
ping -c 2 mvcc.edu
ping -c 5 suny.edu
ping -c 4 slickdeals.net
ping -c 3 dealnews.com
ping -c 1 ubuntu.com
ping -c 4 ask.com
ping -c 2 slickdeals.net
ping -c 5 bbc.co.uk
ping -c 5 gottadeal.com
ping -c 4 ask.com
ping -c 3 google.com
ping -c 4 espn.com
ping -c 2 ask.com
ping -c 3 google.com
ping -c 4 yahoo.com
ping -c 5 hotmail.com
ping -c 1 ask.com
ping -c 3 google.com
ping -c 3 ask.com
ping -c 4 reddit.com
ping -c 5 archive.org
ping -c 5 suny.edu
ping -c 10 slickdeals.net
ping -c 3 dealnews.com
ping -c 4 ubuntu.com
ping -c 3 ask.com
ping -c 3 google.com
ping -c 4 yahoo.com
ping -c 5 bbc.co.uk
ping -c 3 espn.com
ping -c 10 bbc.co.uk
ping -c 40 hotmail.com
ping -c 50 ask.com
ping -c 10 espn.com
ping -c 200 google.com
ping -c 300 hotmail.com
ping -c 200 slashdot.org
ping -c 1000 google.com
ping -c 2000 yahoo.com
ping -c 4000 hotmail.com